---
- name: Install prerequisite packages
  apt:
    state: present
    name:
      - curl
      - gnupg2
      - ca-certificates
      - lsb-release

- name: Import nginx apt key
  apt_key:
    url: https://nginx.org/keys/nginx_signing.key
    state: present

- name: Show distribution version
  debug:
    msg: "{{ ansible_distribution }} | {{ ansible_distribution_release }}"

- name: Add nginx apt repo
  apt_repository:
    repo: "deb http://nginx.org/packages/mainline/ubuntu {{ ansible_distribution_release }} nginx"
    state: present
    update_cache: yes

- name: Install nginx
  apt:
    name: nginx

- name: Copy nginx config file
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: Restart nginx

- name: Enable nginx service running
  service:
    name: nginx
    state: started
    enabled: yes
